/* Static Allocation Table */

/* Inodes for db, dev, tmp directory */

#define FT_DB_DIR_DATABLOCK_NUMBER (SFS_LAST_RESERVED_BLOCK + 1)
#define FT_DB_DIR_INODE_NUMBER (SFS_LAST_RESERVED_INODE + 1)
#define FT_DB_DIR_BLOCK_COUNT 1

#define FT_DEV_DIR_DATABLOCK_NUMBER (FT_DB_DIR_DATABLOCK_NUMBER + FT_DB_DIR_BLOCK_COUNT)
#define FT_DEV_DIR_INODE_NUMBER (FT_DB_DIR_INODE_NUMBER + 1)
#define FT_DEV_DIR_BLOCK_COUNT 1

#define FT_TEMP_DIR_DATABLOCK_NUMBER (FT_DEV_DIR_DATABLOCK_NUMBER + FT_DEV_DIR_BLOCK_COUNT)
#define FT_TEMP_DIR_INODE_NUMBER (FT_DEV_DIR_INODE_NUMBER + 1)
#define FT_TEMP_DIR_BLOCK_COUNT 1


/* Inodes for files in db */

#define FT_DATA_DATABLOCK_NUMBER (FT_TEMP_DIR_DATABLOCK_NUMBER + FT_TEMP_DIR_INODE_NUMBER)
#define FT_DATA_INODE_NUMBER (FT_TEMP_DIR_INODE_NUMBER + 1)
#define FT_DATA_BLOCK_COUNT (1024L*256*100) /* 100 GB of 4KB block */

#define FT_META_DATABLOCK_NUMBER (FT_DATA_DATABLOCK_NUMBER + FT_DATA_BLOCK_COUNT)
#define FT_META_INODE_NUMBER (FT_DATA_INODE_NUMBER + 1)
#define FT_META_BLOCK_COUNT (1024L*256*20) /* 20 GB of 4KB block */

#define FT_LOG_DATABLOCK_NUMBER (FT_META_DATABLOCK_NUMBER + FT_META_BLOCK_COUNT)
#define FT_LOG_INODE_NUMBER (FT_META_INODE_NUMBER + 1)
#define FT_LOG_BLOCK_COUNT (1024L*256*4) /* 4 GB of 4KB block */

#define TOKU_DIR_DATABLOCK_NUMBER (FT_LOG_DATABLOCK_NUMBER + FT_LOG_BLOCK_COUNT)
#define TOKU_DIR_INODE_NUMBER (FT_LOG_INODE_NUMBER + 1)
#define TOKU_DIR_BLOCK_COUNT (1L*256*4) /* 1 MB of 4KB block */

#define TOKU_ENV_DATABLOCK_NUMBER (TOKU_DIR_DATABLOCK_NUMBER + TOKU_DIR_BLOCK_COUNT)
#define TOKU_ENV_INODE_NUMBER (TOKU_DIR_INODE_NUMBER + 1)
#define TOKU_ENV_BLOCK_COUNT (1L*256*4) /* 1 MB of 4KB block */

#define TOKU_LOCK_DATA_DATABLOCK_NUMBER (TOKU_ENV_DATABLOCK_NUMBER + TOKU_ENV_BLOCK_COUNT)
#define TOKU_LOCK_DATA_INODE_NUMBER (TOKU_ENV_INODE_NUMBER + 1)
#define TOKU_LOCK_DATA_BLOCK_COUNT 0

#define TOKU_LOCK_ENV_DATABLOCK_NUMBER (TOKU_LOCK_DATA_DATABLOCK_NUMBER + TOKU_LOCK_DATA_BLOCK_COUNT)
#define TOKU_LOCK_ENV_INODE_NUMBER (TOKU_LOCK_DATA_INODE_NUMBER + 1)
#define TOKU_LOCK_ENV_BLOCK_COUNT 0 

#define TOKU_LOCK_LOGS_DATABLOCK_NUMBER (TOKU_LOCK_ENV_DATABLOCK_NUMBER + TOKU_LOCK_ENV_BLOCK_COUNT)
#define TOKU_LOCK_LOGS_INODE_NUMBER (TOKU_LOCK_ENV_INODE_NUMBER + 1)
#define TOKU_LOCK_LOGS_BLOCK_COUNT 0

#define TOKU_LOCK_RECV_DATABLOCK_NUMBER (TOKU_LOCK_LOGS_DATABLOCK_NUMBER + TOKU_LOCK_LOGS_BLOCK_COUNT)
#define TOKU_LOCK_RECV_INODE_NUMBER (TOKU_LOCK_LOGS_INODE_NUMBER + 1)
#define TOKU_LOCK_RECV_BLOCK_COUNT 0

#define TOKU_LOCK_TEMP_DATABLOCK_NUMBER (TOKU_LOCK_RECV_DATABLOCK_NUMBER + TOKU_LOCK_RECV_BLOCK_COUNT)
#define TOKU_LOCK_TEMP_INODE_NUMBER (TOKU_LOCK_RECV_INODE_NUMBER + 1)
#define TOKU_LOCK_TEMP_BLOCK_COUNT 0

#define TOKU_ROLLBACK_DATABLOCK_NUMBER (TOKU_LOCK_TEMP_DATABLOCK_NUMBER + TOKU_LOCK_TEMP_BLOCK_COUNT)
#define TOKU_ROLLBACK_INODE_NUMBER (TOKU_LOCK_TEMP_INODE_NUMBER + 1)
#define TOKU_ROLLBACK_BLOCK_COUNT 0

/* Inodes for file in dev */

#define DEV_NULL_DATABLOCK_NUMBER (TOKU_ROLLBACK_DATABLOCK_NUMBER + TOKU_ROLLBACK_BLOCK_COUNT)
#define DEV_NULL_INODE_NUMBER (TOKU_ROLLBACK_INODE_NUMBER + 1)
#define DEV_NULL_BLOCK_COUNT 0

